---
title: "1228-0103"
tag: TIL
category: TIL
---
## 1228
# 예외처리(exception handling)


## 프로그램 오류
*오작동을 하거나 비정상적으로 종료되는 경우 이러한 결과를 초래하는 원인을 프로그램 오류 또는 에러라고 한다.*

**에러의 종류**
1. 컴파일 에러 - 컴파일 시에 발생하는 에러
2. 런타임 에러 - 실행 시에 발생하는 에러
3. 논리적 에러 - 실행은 되지만, 의도와 다르게 동작하는 것

* 자바는 실행 시 발생할 수 있는 프로그램 오류를 '에러'와 '예외', 두 가지로 구분하였다.  
**에러** - 프로그램 코드에 의해서 수습될 수 없는 심각한 오류  
**예외** - 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

## 예외 클래스의 계층구조
* 자바에서는 실행 시 발생할 수 있는 오류(Exception과 Error)를 클래스로 정의하였다.
* Exception과 Error클래스 역시 Object 클래스의 자손이다.
* 모든 예외의 최고 조상은 Exception클래스이며, 예외 클래스들은 두 그룹으로 나눠질 수 있다.
	1. Exception클래스와 그 자손들
	2. RuntimeException클래스와 그 자손들

* Exception 클래스들은 주로 **사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외**      
	* 배열의 범위를 벗어남 - ArrayIndexOutOfBoundsException
	* 값이 null인 참조변수의 멤버를 호출 - NullPointerException
	* 클래스간의 형변환 실수 - ClassCastException
	* 정수를 0으로 나눔 - ArithmeticException 등
* RuntimeException클래스들은 주로 **프로그래머의 실수에 의해서 발생할 수 있는 예외**
	* 존재하지 않은 파일의 이름 입력 - FileNotFoundException
	* 실수로 클래스의 이름을 잘못 적음 - ClassNotFoundException
	* 입력한 데이터 형식이 잘못된 경우 - DataFormatException 등

## 예외처리하기 - try-catch문
실행도중 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머가 이에 대한 처리를 미리 해주어야 한다.

### 예외처리  
**정의** - 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것  
**목적** - 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것

> 에러와 예외는 모두 실행 시(runtime) 발생하는 오류이다.

* 발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기'가 받아서 에러의 원인을 화면에 출력

### try-catch문
```java
try {
		//예외가 발생할 가능성이 있는 문장
} catch (Exception1 e1) {
		//Exception1이 발생 시, 처리하기 위한 문장
} catch (Exception2 e2) {
		//Exception2이 발생 시, 처리하기 위한 문장
}
```
* 하나의 try 블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch블럭만 수행
* 일치하는 catch블럭이 없으면 예외는 처리되지  않는다.
* if문과 달리, try블럭이나 catch블럭 내에 포함된 문장이 하나뿐이어도 괄호 생략 불가
* try블럭 또는 catch블럭에 또 다른 try-catch문이 포함될 수 있다.
* 그러나 catch블럭 내에 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참조변수를 사용해서는 안 된다.

## try-catch문에서의 흐름
* try블럭 내에서 예외가 발생한 경우,
	1. 발생한 예외와 일치하는 catch블럭이 있는지 확인
	2. 일치하는 catch블럭을 찾게 되면, catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행
* try블럭 내에서 예외가 발생하지 않은 경우,
	1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속

*try블럭에서 예외가 발생하면, 예외가 발생한 위치 이후에 있는 try블럭의 문장들은 수행되지 않으므로, try블럭에 포함시킬 코드의 범위를 잘 선택해야 한다.*

## 예외의 발생과 catch블럭
1. 예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어 진다.
2. 첫 번째 catch블럭부터 차례로 내려가면서 catch블럭의 괄호()내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof연산자를 이용해서 검사결과가 true인 catch블럭을 만날 때까지 검사한다.
3. 검사결과가 true인 catch블럭을 찾게 되면 블럭에 있는 문장들을 모두 수행하고 try-catch문을 빠져나간다.

**모든 예외 클래스는 Exception클래스의 자손이므로, catch블럭의 괄호()에 Exception클래스 타입의 참조변수를 선언해 놓으면 어떤 종류의 예외가 발생하더라도 이 catch블럭에 의해서 처리된다.**

### printStackTrace()와 getMessage()
*예외가 발생했을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨있고, getMessage()와 printStackTrace()를 통해서 이 정보들을 얻을 수 있다.*

**printStackTrace()** - 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력  
 **getmessage()** -  발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

### 멀티 catch블럭
*JDK 1.7부터 여러 catch블럭을 '|'기호를 이용해서, 하나의 catch블럭으로 합칠 수 있게 되었으며, 이를 '멀티 catch블럭'이라 한다.*
```java
try {
} catch (ExceptionA | ExceptionB) {
	e.printStackTrace();
}
```
* `|`기호로 연결할 수 있는 예외 클래스의 개수에는 제한이 없다.
* 연결된 예외 클래스가 조상과 자손의 관계에 있다면 컴파일 에러가 발생한다.  
-> 불필요한 코드는 제거하라는 의미
* 멀티 catch는 하나의 catch블럭으로 여러 예외를 처리하는 것이기 때문에, 멀티 catch블럭 내에서는 실제로 어떤 예외가 발생한 것인지 알 수 없다. 그래서 예외 클래스들의 공통 분모인 조상 예외 클래스에 선언된 멤버만 사용할 수 있다.

## 예외 발생시키기
1. 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스를 만든 다음  
`Exception e = new Exception("고의로 발생시켰음");`
2. 키워드 throw를 이용해서 예외를 발생시킨다.  
`throw e;`

* Exception인스턴스를 생성할 때, 생성자에 String을 넣어 주면, Exception인스턴스에 메시지로 저장된다.
* Exception클래스들이  발생할 가능성이 있는 문장들에 대해 예외처리를 해주지 않으면 컴파일조차 되지 않는다.
* RuntimeException클래스들에 해당하는 예외는 프로그래머에 의해 실수로 발생하는 것들이기 때문에 예외처리를 강제하지 않는다.  
->  만일 예외처리를 필수로 해야 한다면, 참조 변수와 배열이 사용되는 모든 곳에 예외처리를 해줘야 할 것이다.

**컴파일러가 예외처리를 확인하지 않는 RuntimeException클래스들은 'unchecked예외'라고 부르고, 예외처리를 확인하는 Exception클래스들은 'checked예외'라고 부른다.**
